### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by candidoalbertosilva** [aaroniker/tiny-grid#1]
hello brother,

This plugin not supported native plugin. Please, provide native plugin. Thank's.

**Comment by aaroniker** [comment]
Hi, what do you mean by "native plugin" ?
Whats not working?

**Comment by candidoalbertosilva** [comment]
the plugin was built for wordpress. I do not use wordpress, use tynemce plugin in my code, I would like to implement the tiny-grid in my code. How do I do that ?

**Comment by aaroniker** [comment]
ah ok, not possible so far ... because the tinymce for wordpress isnt exact the same like the standard one
